site_name: SimpleTTS
theme:
  name: material
  palette:
    scheme: slate
    primary: black
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fakerybakery/simpletts
copyright: Copyright &copy; 2024 mrfakename. Licensed under the BSD 3-Clause License.
