site_name: SimpleTTS
theme:
  name: material
  palette:
    scheme: slate
    primary: black
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  generator: false
